### ISSUE TITLE
Tokyo compatible

### ISSUE THREAD

**Issue by tothpaul** [serbod/lazrichview#1]
Hello, you can compile this component under Delphi Tokyo with very few changes

1) add {$IFDEF FPC}/{$ENDIF} around {$mode DELPHI}

2) there's a mistake in Richview.pas, the code from line 459 to 509 should not be inside the IFDEF FPC used for InfoAboutSaD.

Best regards
Paul

**Comment by serbod** [comment]
Thank you very much for bugreport!
